name: Amedas application

on:
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Settings
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          python -m pip install --upgrade pip
          pip install cartopy metpy matplotlib pandas datetime beautifulsoup4

      - name: Plotting
        run: |
          python amedasplot.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git add **/*.png
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add Pictures"
            git push origin main
          fi
